"""empty message

Revision ID: c5c0684cbff6
Revises: fe710f56c56a
Create Date: 2024-04-05 13:14:05.323314

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c5c0684cbff6"
down_revision: Union[str, None] = "fe710f56c56a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "name", existing_type=sa.VARCHAR(length=100), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "name", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    # ### end Alembic commands ###
